server:
  port: 8095

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-permisos
          uri: http://localhost:8082
          predicates:
            - Path=/permisos/**
        - id: servicio-pacientes
          uri: http://localhost:8085
          predicates:
            - Path=/pacientes/**
        - id: servicio-cedulas
          uri: http://localhost:8090
          predicates:
            - Path=/cedulas/**
        - id: servicio-expedientes
          uri: http://localhost:8081
          predicates:
            - Path=/expedientes/**
