server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-expedientes
          uri: http://localhost:8081
          predicates:
            - Path=/expedientes/**
        - id: servicio-permisos
          uri: http://localhost:8082
          predicates:
            - Path=/permisos/**
